### ISSUE TITLE
Error Invalid Argument Exception with DragablzItem 

### ISSUE THREAD

**Issue by b-barry** [ButchersBoy/Dragablz#17] opened 2015-04-02 17:35 UTC
Hello,

First of all, great work for this library. It is very powerful.

I begin a new wpf project and I integrate it.
I have my MainWindows.xaml with a ContentControl where the source is updated by a binding with MainViewModel.
Thanks to this ContentControl and the binding, I manage the navigation into my app.
When I click on a button, I change the source of the ContentControl and switch to a new HomeView ( a user control). 
Into this HomeView, I put a dragablz with some tabs. However, when I drag out a tab, I got a exception and it doesn't create the new windows.  I don't understand why because if I move the code directly to MainWindows, it's working. 
I hope you will help me to understand where is the issues.

Best regards,

**Comment by ButchersBoy** [comment] 2015-04-02 18:09
Can you send me a demo project?

**Comment by b-barry** [comment] 2015-04-02 20:49
Hello,

Thanks you for your quick answer.

I have just created a demo project that you can find here:
https://github.com/b-barry/MahAppsDragablz/tree/dev/demo-project

I think that my error comes from InterTabClient. I don't implement my custom because I thought that the basic would be enough.

Thanks you for your helps:

Best regards

**Comment by ButchersBoy** [comment] 2015-04-03 05:50
Ok. I'm away for a few days so I'll have a look next week.

**Comment by ButchersBoy** [comment] 2015-04-06 17:28
OK, had a look at your code.  Your setup has highlighted a "shortfall" in the DefaultInterTabClient. Dragablz is expecting the TabablzControl to be immediately there when the new Window loads.  But in your case it is not, because it resides inside your main ContentControl and data binding has not yet completed, and thus the content has not yet been created...so no TabablzControl is ready.

I can fix this by getting the DefaultInterTabClient to wait for the initial databinding pass before it tries to find the TabablzControl.  I think this is reasonable, as that class is designed to get people up and running out of the box quickly.  For more advanced scenarios a custom version can always be provided.

I've just checked in the fix, so look out for the next build and let me know if it's working for you.

**Comment by b-barry** [comment] 2015-04-06 18:37
Hello,

Thank you for your quick response and your search.
I kept searching on my side. I tried to create a custom InterTabClient to create a new host with a  template Windows like in your sample. However, it did not succeed .
I still got the same exception.
From this, it occurred to me one question:
is it possible to release a tab, create a new host windows that do not possess a TabControl in its xaml ie set to null the 2nd parameter constructor newhost? 
After go out,  would be possible to put again this tab in its initial view ?

Best regards

**Comment by ButchersBoy** [comment] 2015-04-06 19:03
No, the INewTabHost must be correctly populated with the tab control; Dragablz will validate this and if its not, will throw an error.  It's quite a fundamental requirement that it can get the Tab control straight away.

But, if you update Dragablz from nuget in your demo project (https://github.com/b-barry/MahAppsDragablz/tree/dev/demo-project), you will see your original issue is fixed:

![dragablz-issue17-fix](https://cloud.githubusercontent.com/assets/658107/7010252/9c5e2742-dc97-11e4-95d2-3572600b7e5a.gif)

As stated above, the DefaultInterTabClient will no wait for the initial data bind which will give your TabControl chance to be loaded.

**Closed** 2015-04-08 19:18 UTC

**Comment by b-barry** [comment] 2015-04-09 18:50
Hello,


Thank you very much for your work.
I will update my project as soon.
I understand the fundamental requirement, it is important.
A latest question, if I use a newhost that creates the new tab into dragablz Windows, I will be able to put again this tab in its initial view  ?

Thank you

**Comment by ButchersBoy** [comment] 2015-04-09 19:40
Yeah you should be able to...you can intercept at that point so you can put the tab in whatever state you like...so long as it exists.

**Comment by BorisPetelj** [comment] 2016-10-08 10:34
Hello,

First I must say, the framework is great. It's just the thing I needed on project. 

I ran into almost the same problem as @b-barry. When trying to drag out the tab, exception (Unable to ascrtain tab control.) is thrown. 

The difference is that i use Pages whose Content and DataContext are set as appropriate properties on window itself for the purpose of navigation. One such Page contains TabablzControl with InterTabController and Tabs. 
The page is first displayed as expected but mentioned exception is thrown on dragging the tab out. 

The thing is, when I downloaded your demo project (above showing working gif), the same exception is thrown. Current Dragablz version in my project is 0.0.3.171, but nevertheless, demo project has 0.0.1.107 and not working on my machine. 

Can you point me in the right direction?  @b-barry never confirmed that the issue is fixed with newer Dragablz version. 

Thank You for providing such great support!
Best regards, Boris.

**Comment by ButchersBoy** [comment] 2016-10-09 07:05
Hi,the demo might be out of date, but this is still likely a problem in your app setup.  If you post a sample  GitHub repo I will try and take a look.

**Comment by BorisPetelj** [comment] 2016-10-09 07:42
This is the demo project. 
https://github.com/BorisPetelj/DragablzDemo

Thank you for your time.

**Comment by ButchersBoy** [comment] 2016-10-14 10:59
If you read the inner exception: 

{"Unable to ascertain tab control."}

When your new Window is created, the tab control is not created.

From Dragablz perspective, when w tab is torn out, and new Window must be created, with a tab control immediately accessible, so the mouse can be recaptured and the users dragging motion can be completed.

It looks like you are only using your "Switcher" on app start up.  You might want to consider implementing a custom "IInterTabClient" which will generated the new Window and get the tab control ready.

**Comment by BorisPetelj** [comment] 2016-10-16 11:59
I understand. 
I implemented the "IInterTabClient", which is called when tearing out a tab. It creates new dragablz window (my custom one) with tab control and it's working fine. However, I have the following issue:

- When tab is torn out, new template window is created with IInterTabClient support.
- When this tab is restored back to original window in split mode, everything is ok. 
- Then, when trying to tear out the same tab again (from split mode), IInterTabClient is not called thus original window is created instead of my custom template window for teared tab. Since the original window does not have tab control (first issue) the "Unable to ascertain tab control." is thrown. 

_Note that if you restore tab back to original window (aside other tabs), you can tear it again with no exception._

_If I move tab control to window from page, exception is not thrown but orginal (main) window is created, which I want to avoid._

I tried to investigate provided examples and found out about "dockablz:Layout.BranchTemplate" which is used for creating new tab control when tab is restored in split mode.
I used this component in my custom template window, also with IInterTabClient, which I hoped to solve the issue, but it keeps creating the original window (and thus throwing mentioned exception) when tearing tab the second time.

I updated demo project (link above), so if you can take a look I would greatly appreciate.

Also, is there a way to consolidate tabs that are created with IInterTabClient back to original window when closed?

Thank you for support, Boris.

**Comment by ButchersBoy** [comment] 2016-10-17 09:22
``` ConsolidateOrphanedItems ```

**Comment by Maradaehne** [comment] 2017-02-06 15:30
Hi, 
I got a similiar error but a step later.

- When tab is torn out, new template window is created with IInterTabClient support.

- When this tab is restored back to original window in split mode, everything is ok.

- I put the tab back from split mode to original tabcontrol, everything is ok

- When i try to tear the same tab out again a target of invocation Exception is thrown 

> Message: Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.RoutedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at Dragablz.DragablzItem.ThumbOnDragDelta(Object sender, DragDeltaEventArgs dragDeltaEventArgs) in C:\projects\dragablz\Dragablz\DragablzItem.cs:line 547
   at System.Windows.Controls.Primitives.DragDeltaEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.Thumb.OnMouseMove(MouseEventArgs e)
   at System.Windows.UIElement.OnMouseMoveThunk(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

>  InnerException:
> 
> Message:
> 
> No parameterless constructor defined for this object.
> Stacktrace:
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at Dragablz.DefaultInterTabClient.GetNewHost(IInterTabClient interTabClient, Object partition, TabablzControl source) in C:\projects\dragablz\Dragablz\DefaultInterTabClient.cs:line 14
>    at Dragablz.TabablzControl.MonitorBreach(DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1195
>    at Dragablz.TabablzControl.ItemDragDelta(Object sender, DragablzDragDeltaEventArgs e) in C:\projects\dragablz\Dragablz\TabablzControl.cs:line 1112
> 

Why is the first tearing out successfull, but the second is  failing? It seems that dragablz is ignoring the custom tabclient.

Thanks in advance

**Comment by ButchersBoy** [comment] 2017-02-06 15:43
*Be very wary of your bindings* Use Snoop first to check that InterTabController is setup as you expected.

**Comment by Maradaehne** [comment] 2017-02-07 01:47
I tried to put it in a smaller project to reproduce the mistake and check it with snoop.

Unfortunately I am failing a step earlier now. This means, I can tear out the tab and restore it back to the original window in split mode, everything is ok. But when I want to tear out the same tab again the exception is thrown. 

I checked with snoop and the Intertab Controller is set to the DefaultInterTabClient after the tab was restored in split mode in the original window, but it should be my custom tabclient. There is something that i am missing. If you could have look to it and give me a hint what i am missing  I would be really grateful.

https://github.com/Maradaehne/DragablzIssue

**Comment by Maradaehne** [comment] 2017-02-08 07:57
I found a way to get it work, but is it the intended way to set the IntertabController in this way:

>         public INewTabHost<Window> GetNewHost(IInterTabClient interTabClient, object partition, TabablzControl source)
>         {
>             var view = new TableMovementTabWindow();
>             var model = new TableMovementTabViewModel(interTabClient, partition);
>             view.DataContext = model;
>             view.TabsContainer.InterTabController.InterTabClient = source.InterTabController.InterTabClient;
>             return new NewTabHost<Window>(view, view.TabsContainer);
>         }

**Comment by ButchersBoy** [comment] 2017-02-08 08:29
That's fine, you can set it however your want.
